soc: qcom: rpmh-rsc: Fix compilation after merging v5.10.224
../drivers/soc/qcom/rpmh-rsc.c:677:38: error: use of undeclared identifier 'flags'
  677 |                 spin_unlock_irqrestore(&drv->lock, flags);
      |                                                    ^

This is the part that was left out when merging commit eedd9fd986415b3cc62b96876ad5d41d3ed56127.

Signed-off-by: fjrXTR <fajarslebew31@gmail.com>